insert into debt (customer_id,amount,remarks) values (162, 800.00,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (165, 2870.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (174, 150.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (196, 735.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (194, 105.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (661, 180.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (534, 14000.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (301, 4900.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values ( 62, 600.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (154, 525.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (252, 350.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (721, 6650.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (710, 35.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (699, 1155.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (106, 2040.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (469, 580.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (142, 100.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values ( 29, 350.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (580, 3605.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (381, 17308.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (688, 525.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (308, 125.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (662, 455.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (188, 1400.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values ( 27, 1440.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (689, 15.00 ,'Beginning Balance');
