insert into debt (customer_id,amount,remarks) values (162, 800.00,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (165, 2800.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (196, 735.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (194, 1050.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (534, 14490.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (301, 4900.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values ( 62, 600.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (154, 525.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (721, 7700.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (699, 1050.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (106, 1080.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (469, 300.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (142, 100.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values ( 29, 350.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (580, 2800.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (381, 17200.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (688, 450.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (308, 125.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (662, 455.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (188, 1400.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values ( 27, 1440.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (793, 2300.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (454, 3500.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (763, 210.00 ,'Beginning Balance');
insert into debt (customer_id,amount,remarks) values (772, 2450.00 ,'Beginning Balance');
